# Generated by Django 5.2.6 on 2026-03-26 22:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlphaSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ticker', models.CharField(max_length=20)),
                ('signal_direction', models.CharField(max_length=10)),
                ('entry_price', models.FloatField(blank=True, null=True)),
                ('ceo_approved_lot', models.FloatField(blank=True, null=True)),
                ('sl', models.FloatField(blank=True, null=True)),
                ('tp', models.FloatField(blank=True, null=True)),
                ('pnl', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending AI/CEO Check'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXECUTED', 'Sent to Broker'), ('CLOSED', 'Closed')], default='PENDING', max_length=20)),
                ('analysis_details', models.TextField(default='{}')),
                ('pre_trade_checklist', models.TextField(default='{}')),
                ('review_data', models.TextField(default='{}')),
                ('images', models.TextField(default='[]')),
                ('result_images', models.TextField(default='[]')),
                ('htf_trend', models.CharField(blank=True, max_length=20, null=True)),
                ('market_phase', models.CharField(blank=True, max_length=50, null=True)),
                ('dealing_range', models.CharField(blank=True, max_length=100, null=True)),
                ('narrative', models.TextField(blank=True, null=True)),
                ('scenario_type', models.CharField(blank=True, max_length=50, null=True)),
                ('trade_class', models.CharField(blank=True, max_length=10, null=True)),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForexPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=10, unique=True)),
                ('current_rate', models.DecimalField(decimal_places=5, max_digits=12, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Forex Pairs',
                'ordering': ['pair'],
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('market_context', models.TextField(blank=True, null=True)),
                ('key_levels', models.TextField(blank=True, null=True)),
                ('trade_plan', models.TextField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=100, null=True)),
                ('lessons_learned', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('attached_image', models.ImageField(blank=True, null=True, upload_to='insights/images/')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='insights/files/')),
            ],
        ),
        migrations.CreateModel(
            name='MacroData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('country', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Macro Data',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='MacroDirective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MissedTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=20, null=True)),
                ('direction', models.CharField(default='BUY', max_length=10)),
                ('reason', models.CharField(max_length=50, null=True)),
                ('notes', models.TextField(null=True)),
                ('image_paths', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Portfolio', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('buy_date', models.DateField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuantAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('strategy_type', models.CharField(choices=[('BALANCED', 'Balanced Alpha'), ('AGGRESSIVE', 'Aggressive Growth'), ('CONSERVATIVE', 'Conservative Hedge')], default='BALANCED', max_length=20)),
                ('balance', models.FloatField(default=0)),
                ('equity', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal Operation'), ('REDUCED', 'Reduced Risk (-50%)'), ('HALT', 'System Liquidation / Halt')], default='NORMAL', max_length=20)),
                ('max_drawdown', models.FloatField(default=0.1)),
                ('current_drawdown', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RadarBlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('configuration', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyOutlook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(unique=True)),
                ('weekly_bias', models.CharField(default='NEUTRAL', max_length=20)),
                ('execution_script', models.TextField(blank=True)),
                ('fa_bias', models.TextField(default='{}')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_profit_monthly', models.FloatField(default=5.0)),
                ('max_drawdown_limit', models.FloatField(default=10.0)),
                ('max_risk_per_trade', models.FloatField(default=1.0)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='finance_dashboard.quantaccount')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_rate', models.FloatField(default=0)),
                ('profit_factor', models.FloatField(default=1.0)),
                ('oci_index', models.FloatField(default=0)),
                ('total_interventions', models.IntegerField(default=0)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='finance_dashboard.quantaccount')),
            ],
        ),
        migrations.CreateModel(
            name='BehaviorMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_streak', models.IntegerField(default=0)),
                ('avg_risk_per_trade', models.FloatField(default=0)),
                ('trade_frequency_24h', models.IntegerField(default=0)),
                ('oci_score', models.FloatField(default=0)),
                ('state', models.CharField(default='STABLE', max_length=20)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance_dashboard.quantaccount')),
            ],
        ),
        migrations.CreateModel(
            name='BehaviorAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_label', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=10)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_logs', to='finance_dashboard.quantaccount')),
            ],
        ),
        migrations.CreateModel(
            name='RiskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_logs', to='finance_dashboard.alphasignal')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=4)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('PENDING', 'Pending')], default='OPEN', max_length=10)),
                ('open_rate', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('close_rate', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('stoploss', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('takeprofit', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('open_date', models.DateTimeField(auto_now_add=True)),
                ('forex_pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance_dashboard.forexpair')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(default=1)),
                ('week_start_date', models.DateField()),
                ('total_trades', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('net_pnl', models.FloatField(default=0.0)),
                ('fa_accuracy', models.IntegerField(default=5)),
                ('ta_accuracy', models.IntegerField(default=5)),
                ('fusion_score', models.IntegerField(default=5)),
                ('review_details', models.TextField(default='{}')),
            ],
            options={
                'unique_together': {('account_id', 'week_start_date')},
            },
        ),
    ]
