# Generated by Django 5.2.6 on 2026-03-23 12:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlphaSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ticker', models.CharField(max_length=20)),
                ('signal_direction', models.CharField(max_length=10)),
                ('entry_price', models.FloatField(blank=True, null=True)),
                ('sl', models.FloatField(blank=True, null=True)),
                ('tp', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.IntegerField(default=0)),
                ('ceo_approved_lot', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending AI/CEO Check'), ('APPROVED', 'Approved (Waiting to Fire)'), ('REJECTED', 'Rejected'), ('EXECUTED', 'Sent to Broker'), ('CLOSED', 'Position Closed')], default='PENDING', max_length=20)),
                ('ticket_id', models.CharField(blank=True, max_length=50, null=True)),
                ('realized_pnl', models.FloatField(default=0.0)),
                ('pnl', models.FloatField(blank=True, default=0.0, null=True)),
                ('analysis_details', models.TextField(default='{}')),
                ('pre_trade_checklist', models.TextField(default='{}')),
                ('risk_data', models.TextField(default='{}')),
                ('images', models.TextField(default='[]')),
                ('result_images', models.TextField(default='[]')),
                ('review_data', models.TextField(default='{}')),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('htf_trend', models.CharField(blank=True, max_length=50, null=True)),
                ('market_phase', models.CharField(blank=True, max_length=50, null=True)),
                ('dealing_range', models.CharField(blank=True, max_length=50, null=True)),
                ('narrative', models.TextField(blank=True, null=True)),
                ('scenario_type', models.CharField(blank=True, max_length=50, null=True)),
                ('trade_class', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForexPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=10, unique=True)),
                ('current_rate', models.DecimalField(decimal_places=5, max_digits=12, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Forex Pairs',
                'ordering': ['pair'],
            },
        ),
        migrations.CreateModel(
            name='MacroData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('country', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Macro Data',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='MacroDirective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('issued_by', models.CharField(default='CEO', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MissedTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=20)),
                ('direction', models.CharField(max_length=10)),
                ('reason', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('image_paths', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Portfolio', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('buy_date', models.DateField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Portfolios',
                'ordering': ['-buy_date'],
            },
        ),
        migrations.CreateModel(
            name='QuantAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('balance', models.FloatField(default=0.0)),
                ('equity', models.FloatField(default=0.0)),
                ('margin', models.FloatField(default=0.0)),
                ('free_margin', models.FloatField(default=0.0)),
                ('margin_level', models.FloatField(default=0.0)),
                ('account_currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(default='NORMAL', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RadarBlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('direction', models.CharField(max_length=10)),
                ('active_tags', models.TextField(default='[]')),
                ('is_alerting', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('SETUP', 'Entry Models (Setup)'), ('EXIT_STRAT', 'Exit Strategies'), ('CONTEXT_TAG', 'Context Tags'), ('SCENARIO_TYPE', 'Scenario Types'), ('RISK_MODEL', 'Risk Profiles (Kelly)')], max_length=20)),
                ('configuration', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyOutlook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(unique=True)),
                ('market_sentiment', models.CharField(default='MIXED', max_length=50)),
                ('weekly_bias', models.CharField(default='NEUTRAL', max_length=50)),
                ('execution_script', models.TextField(blank=True, null=True)),
                ('fa_bias', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Daily', 'Daily Analysis'), ('Weekly', 'Weekly Outlook'), ('Monthly', 'Monthly Review'), ('Macro', 'Macro Update'), ('Technical', 'Technical Analysis'), ('Trade Idea', 'Trade Idea')], default='Daily', max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('market_context', models.TextField(help_text='Bối cảnh vĩ mô, xu hướng chính')),
                ('key_levels', models.TextField(help_text='Kháng cự, hỗ trợ, vùng cung cầu')),
                ('trade_plan', models.TextField(help_text='Kế hoạch giao dịch cụ thể')),
                ('result', models.CharField(choices=[('Pending', 'Pending'), ('Win', 'Win'), ('Loss', 'Loss'), ('Break Even', 'Break Even'), ('Missed', 'Missed')], default='Pending', max_length=20)),
                ('lessons_learned', models.TextField(blank=True, help_text='Bài học rút ra sau giao dịch', null=True)),
                ('tags', models.CharField(blank=True, help_text='VD: EURUSD, FOMC, Trend Following', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('attached_image', models.ImageField(blank=True, null=True, upload_to='insight_images/%Y/%m/%d/')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='insight_files/%Y/%m/%d/')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_profit_monthly', models.FloatField(default=5.0)),
                ('max_drawdown_limit', models.FloatField(default=10.0)),
                ('max_risk_per_trade', models.FloatField(default=1.0)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='finance_dashboard.quantaccount')),
            ],
        ),
        migrations.CreateModel(
            name='RiskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_logs', to='finance_dashboard.alphasignal')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=4)),
                ('open_rate', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('close_rate', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('stoploss', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('takeprofit', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('open_date', models.DateTimeField(auto_now_add=True)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('PENDING', 'Pending')], default='OPEN', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ref', models.CharField(blank=True, max_length=50, null=True)),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('forex_pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance_dashboard.forexpair')),
            ],
            options={
                'verbose_name_plural': 'Trades',
                'ordering': ['-open_date'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(unique=True)),
                ('total_trades', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('net_pnl', models.FloatField(default=0.0)),
                ('fa_accuracy', models.IntegerField(default=5)),
                ('ta_accuracy', models.IntegerField(default=5)),
                ('fusion_score', models.IntegerField(default=5)),
                ('review_details', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_dashboard.quantaccount')),
            ],
        ),
    ]
