# Generated by Django 5.2.6 on 2026-03-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_dashboard', '0002_alter_insight_options_alter_portfolio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alphasignal',
            name='analysis_details',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='alphasignal',
            name='dealing_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alphasignal',
            name='exit_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alphasignal',
            name='htf_trend',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alphasignal',
            name='images',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='alphasignal',
            name='market_phase',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alphasignal',
            name='narrative',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alphasignal',
            name='pnl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alphasignal',
            name='pre_trade_checklist',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='alphasignal',
            name='result_images',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='alphasignal',
            name='review_data',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='alphasignal',
            name='scenario_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alphasignal',
            name='sl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alphasignal',
            name='tp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alphasignal',
            name='trade_class',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='missedtrade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='missedtrade',
            name='direction',
            field=models.CharField(default='BUY', max_length=10),
        ),
        migrations.AddField(
            model_name='missedtrade',
            name='image_paths',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='missedtrade',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='systemlibrary',
            name='configuration',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='systemlibrary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyoutlook',
            name='execution_script',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklyoutlook',
            name='fa_bias',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='weeklyoutlook',
            name='weekly_bias',
            field=models.CharField(default='NEUTRAL', max_length=20),
        ),
        migrations.AddField(
            model_name='weeklyreview',
            name='account_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='weeklyreview',
            name='fa_accuracy',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='weeklyreview',
            name='fusion_score',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='weeklyreview',
            name='net_pnl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weeklyreview',
            name='review_details',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='weeklyreview',
            name='ta_accuracy',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='weeklyreview',
            name='total_trades',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weeklyreview',
            name='win_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='missedtrade',
            name='pair',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='missedtrade',
            name='reason',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyreview',
            name='week_start_date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyreview',
            unique_together={('account_id', 'week_start_date')},
        ),
    ]
