# Generated by Django 5.2.6 on 2026-03-16 09:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_dashboard', '0017_portfolio_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.FloatField(default=10000.0)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('mql5_path', models.CharField(blank=True, default='', max_length=500)),
                ('lot_size', models.FloatField(default=100000.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_daily_risk_percent', models.FloatField(default=2.0)),
                ('max_concurrent_risk_r', models.FloatField(default=5.0)),
                ('mode', models.CharField(default='NORMAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('image_path', models.CharField(blank=True, max_length=500)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountWeight',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='finance_dashboard.quantaccount')),
                ('weight_percent', models.FloatField(default=0.0)),
                ('status', models.CharField(default='NORMAL', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioRiskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=20)),
                ('direction', models.CharField(max_length=10)),
                ('requested_vol', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_dashboard.quantaccount')),
            ],
        ),
        migrations.CreateModel(
            name='QuantScenario',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outlook_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pair', models.CharField(max_length=20)),
                ('direction', models.CharField(max_length=10)),
                ('setup_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('entry_price', models.FloatField(default=0.0)),
                ('sl_price', models.FloatField(default=0.0)),
                ('tp_price', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.01)),
                ('pnl', models.FloatField(default=0.0)),
                ('exit_price', models.FloatField(default=0.0)),
                ('close_time', models.DateTimeField(blank=True, null=True)),
                ('analysis_details', models.JSONField(blank=True, default=dict)),
                ('pre_trade_checklist', models.JSONField(blank=True, default=dict)),
                ('risk_data', models.JSONField(blank=True, default=dict)),
                ('images', models.JSONField(blank=True, default=list)),
                ('result_images', models.JSONField(blank=True, default=list)),
                ('review_data', models.JSONField(blank=True, default=dict)),
                ('execution_score', models.FloatField(default=0.0)),
                ('htf_trend', models.CharField(blank=True, max_length=50)),
                ('market_phase', models.CharField(blank=True, max_length=50)),
                ('dealing_range', models.CharField(blank=True, max_length=50)),
                ('narrative', models.TextField(blank=True)),
                ('scenario_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_dashboard.quantaccount')),
            ],
        ),
    ]
