# Generated by Django 5.2.6 on 2025-10-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_dashboard', '0017_portfolio_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='insight',
            name='attached_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
