# Generated by Django 5.2.6 on 2026-03-17 05:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_dashboard', '0018_quantaccount_portfoliosetting_systemlibrary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissedTrade',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.IntegerField(default=1)),
                ('week_start_date', models.DateField()),
                ('pair', models.CharField(max_length=20)),
                ('direction', models.CharField(max_length=10)),
                ('reason', models.CharField(max_length=100)),
                ('analysis_details', models.TextField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyOutlook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(default=1)),
                ('week_start_date', models.DateField()),
                ('final_bias', models.CharField(default='NEUTRAL', max_length=50)),
                ('script_plan', models.TextField(blank=True, null=True)),
                ('ta_bias', models.TextField(blank=True, null=True)),
                ('fa_bias', models.TextField(default='{}')),
            ],
            options={
                'unique_together': {('account_id', 'week_start_date')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(default=1)),
                ('week_start_date', models.DateField()),
                ('total_trades', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('net_pnl', models.FloatField(default=0.0)),
                ('fa_accuracy', models.IntegerField(default=5)),
                ('ta_accuracy', models.IntegerField(default=5)),
                ('fusion_score', models.IntegerField(default=5)),
                ('review_details', models.TextField(default='{}')),
            ],
            options={
                'unique_together': {('account_id', 'week_start_date')},
            },
        ),
    ]
