# Generated by Django 5.2.6 on 2026-03-19 03:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_dashboard', '0019_missedtrade_weeklyoutlook_weeklyreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlphaSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('signal_direction', models.CharField(max_length=10)),
                ('win_rate', models.FloatField(default=0.0)),
                ('rr_ratio', models.FloatField(default=0.0)),
                ('is_macro_aligned', models.BooleanField(default=True, help_text='False = LỆNH BỘI PHẢN. Đi ngược Macro Outlook.')),
                ('kelly_recommended_lot', models.FloatField(default=0.0, help_text='Đạn tối đa Kelly cho phép')),
                ('ceo_approved_lot', models.FloatField(blank=True, default=0.0, help_text='Đạn thực tế CEO nạp', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'CHỜ DUYỆT (Radar)'), ('APPROVED', 'ĐÃ DUYỆT (Execute Node)'), ('REJECTED', 'BÁC BỎ (Thùng rác)'), ('EXECUTED', 'ĐANG CHẠY (Sàn MT5)'), ('CLOSED', 'CHỐT SỔ (Sổ cái PnL)')], default='PENDING', max_length=15)),
                ('ticket_id', models.CharField(blank=True, help_text='Mã vé trên MT5', max_length=50, null=True)),
                ('realized_pnl', models.FloatField(default=0.0, help_text='Tiền tươi thóc thật')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MacroDirective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(help_text='VD: XAUUSD, EURJPY', max_length=20)),
                ('direction', models.CharField(choices=[('BUY', 'LONG (BULLISH)'), ('SELL', 'SHORT (BEARISH)'), ('NEUTRAL', 'STAND CLEAR (Đứng ngoài)')], max_length=10)),
                ('week_start', models.DateField(default=django.utils.timezone.now, help_text='Ngày bắt đầu hiệu lực')),
                ('is_active', models.BooleanField(default=True, help_text='Tắt đi nếu sếp đổi ý')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
