# Generated by Django 5.2.6 on 2026-03-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_dashboard', '0020_alphasignal_macrodirective'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyoutlook',
            old_name='script_plan',
            new_name='execution_script',
        ),
        migrations.RenameField(
            model_name='weeklyoutlook',
            old_name='final_bias',
            new_name='weekly_bias',
        ),
        migrations.AlterUniqueTogether(
            name='weeklyoutlook',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='weeklyoutlook',
            name='market_sentiment',
            field=models.CharField(default='MIXED', max_length=50),
        ),
        migrations.AddField(
            model_name='weeklyoutlook',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='weeklyoutlook',
            name='week_start',
            field=models.DateField(default='2026-01-01', unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='weeklyoutlook',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='weeklyoutlook',
            name='fa_bias',
        ),
        migrations.RemoveField(
            model_name='weeklyoutlook',
            name='ta_bias',
        ),
        migrations.RemoveField(
            model_name='weeklyoutlook',
            name='week_start_date',
        ),
    ]
