# Generated by Django 5.2.6 on 2026-03-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_dashboard', '0021_rename_script_plan_weeklyoutlook_execution_script_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyoutlook',
            name='fa_bias',
            field=models.TextField(blank=True, null=True),
        ),
    ]
