# Generated by Django 5.2.6 on 2026-03-20 12:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_dashboard', '0022_weeklyoutlook_fa_bias'),
    ]

    operations = [
        migrations.AddField(
            model_name='alphasignal',
            name='pnl',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='alphasignal',
            name='ceo_approved_lot',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='alphasignal',
            name='is_macro_aligned',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alphasignal',
            name='kelly_recommended_lot',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='alphasignal',
            name='realized_pnl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='alphasignal',
            name='status',
            field=models.CharField(choices=[('PENDING', 'CHỜ DUYỆT (Radar)'), ('APPROVED', 'ĐÃ DUYỆT (Execute Node)'), ('REJECTED', 'BÁC BỎ (Thùng rác)'), ('EXECUTED', 'ĐANG CHẠY (Sàn MT5)'), ('CLOSED', 'CHỐT SỐ (Số cái PnL)')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='alphasignal',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='macrodirective',
            name='direction',
            field=models.CharField(choices=[('BUY', 'LONG (BULLISH)'), ('SELL', 'SHORT (BEARISH)'), ('NEUTRAL', 'STAND CLEAR')], max_length=10),
        ),
        migrations.AlterField(
            model_name='macrodirective',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='macrodirective',
            name='week_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
