# Generated by Django 5.2.6 on 2026-03-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_dashboard', '0023_alphasignal_pnl_alter_alphasignal_ceo_approved_lot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadarBlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('direction', models.CharField(max_length=10)),
                ('active_tags', models.JSONField(default=list)),
                ('is_alerting', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('timestamp', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
